export type Project = {
  id: string;
  title: string;
  categories: string;
  year: string;
  image: string;
};

export const projects: Project[] = [
  {
    id: "rexona",
    title: "Rexona Brand Refresh",
    categories: "Branding, Website",
    year: "2025",
    image: "/images/rexona.jpg",
  },
  {
    id: "coca-cola",
    title: "Coca-Cola Sustainability Initiative",
    categories: "Branding, Social Media",
    year: "2023",
    image: "/images/coca-cola.jpg",
  },
  {
    id: "nike-air-max",
    title: "Nike Air Max 2023 Launch",
    categories: "Fashion, Website",
    year: "2023",
    image: "/images/nike-air-max.jpg",
  },
  {
    id: "samsung-galaxy",
    title: "Samsung Galaxy Z Series",
    categories: "Technology, Advertising",
    year: "2023",
    image: "/images/samsung-galaxy.jpg",
  },
  {
    id: "mont-blanc",
    title: "Mont Blanc Jacquard Campaign",
    categories: "Fashion, Website",
    year: "2024",
    image: "/images/mont-blanc.png",
  },
  {
    id: "adidas-parley",
    title: "Adidas X Parley Collaboration",
    categories: "Fashion, Website",
    year: "2024",
    image: "/images/adidas-parley.jpg",
  },
  {
    id: "apple-iphone",
    title: "Apple iPhone 16 Event",
    categories: "Technology, Event",
    year: "2024",
    image: "/images/apple-iphone.jpg",
  },
  {
    id: "starbucks",
    title: "Starbucks Fall Menu Promotion",
    categories: "Food & Beverage, Social Media",
    year: "2023",
    image: "/images/starbucks.jpg",
  },
  {
    id: "bmw-electric",
    title: "BMW Electric Series Reveal",
    categories: "Automotive, Website",
    year: "2024",
    image: "/images/bmw-electric.jpg",
  },
  {
    id: "netflix",
    title: "Netflix Original Series Launch",
    categories: "Entertainment, Social Media",
    year: "2023",
    image: "/images/netflix.jpg",
  },
  {
    id: "pepsi-zero",
    title: "Pepsi Zero Sugar Campaign",
    categories: "Branding, Advertising",
    year: "2023",
    image: "/images/pepsi-zero.jpg",
  },
  {
    id: "loreal",
    title: "L'Oreal Beauty Innovations",
    categories: "Cosmetics, Website",
    year: "2024",
    image: "/images/loreal.jpg",
  },
  {
    id: "playstation",
    title: "Sony PlayStation 5 Update",
    categories: "Gaming, Advertising",
    year: "2023",
    image: "/images/playstation.png",
  },
  {
    id: "rolex-daytona",
    title: "Rolex Daytona Release",
    categories: "Luxury, Event",
    year: "2024",
    image: "/images/rolex-daytona.jpg",
  },
  {
    id: "dior-fragrance",
    title: "Dior Sauvage Rebrand",
    categories: "Luxury, Branding",
    year: "2024",
    image: "/images/dior-fragrance.jpg",
  },
  {
    id: "tesla-cybertruck",
    title: "Tesla Cybertruck Launch",
    categories: "Automotive, Website",
    year: "2024",
    image: "/images/tesla-cybertruck.png",
  },
  {
    id: "gucci-archives",
    title: "Gucci Archives Exhibition",
    categories: "Fashion, Event",
    year: "2023",
    image: "/images/gucci-archives.png",
  },
  {
    id: "spotify-wrapped",
    title: "Spotify Wrapped 2024",
    categories: "Entertainment, Social Media",
    year: "2024",
    image: "/images/spotify-wrapped.jpg",
  },
  {
    id: "heineken-zero",
    title: "Heineken Silver Campaign",
    categories: "Food & Beverage, Advertising",
    year: "2023",
    image: "/images/heineken-zero.jpg",
  },
  {
    id: "chanel-no5",
    title: "Chanel N°5 Centenary",
    categories: "Luxury, Website",
    year: "2024",
    image: "/images/chanel-no5.jpg",
  },
  {
    id: "ikea-sustainability",
    title: "IKEA Life at Home Report",
    categories: "Retail, Branding",
    year: "2023",
    image: "/images/ikea-sustainability.png",
  },
  {
    id: "porsche-911",
    title: "Porsche 911 60th Anniversary",
    categories: "Automotive, Event",
    year: "2023",
    image: "/images/porsche-911.png",
  },
  {
    id: "airbnb-icons",
    title: "Airbnb Icons Experience",
    categories: "Travel, Website",
    year: "2024",
    image: "/images/airbnb-icons.jpg",
  },
  {
    id: "prada-linea-rossa",
    title: "Prada Linea Rossa Drop",
    categories: "Fashion, Social Media",
    year: "2025",
    image: "/images/prada-linea-rossa.png",
  },
  {
    id: "nasa-artemis",
    title: "NASA Artemis Visual Identity",
    categories: "Technology, Branding",
    year: "2024",
    image: "/images/nasa-artemis.png",
  },
  {
    id: "omega-seamaster",
    title: "Omega Seamaster Diver Campaign",
    categories: "Luxury, Advertising",
    year: "2025",
    image: "/images/omega-seamaster.png",
  },
  {
    id: "new-balance-1906",
    title: "New Balance 1906R Launch",
    categories: "Fashion, Website",
    year: "2023",
    image: "/images/new-balance-1906.jpg",
  },
  {
    id: "patagonia-worn-wear",
    title: "Patagonia Worn Wear Initiative",
    categories: "Retail, Branding",
    year: "2024",
    image: "/images/patagonia-worn-wear.png",
  },
];
